# Putting all the configuration values related to the POLYUSD Oracle


properties:
  ropsten:
    contract_name: PolyOracle
    contract_address: "0xec1819a8e4f36d2f4e4bf24165d8aa363588ebd7"
    threshold_time: 3       # In Hours
  rinkeby:
    contract_name: PolyOracle
    contract_address:
    threshold_time: 3       # In Hours
  kovan:
    contract_name: PolyOracle
    contract_address: "0xC9b54026C14D7E29d6F3D72AE64049EFb45e390c"
    threshold_time: 3       # In Hours
  mainnet:
    contract_name: PolyOracle
    contract_address:
    threshold_time: 3       # In Hours
  ganache:
    contract_name: MockPolyOracle
    contract_address: "0x4ba3ed8baedbedc3cc65abd5466ae276f47aa345"
    threshold_time: 0

choosen_network: ganache

aws_email_settings:
  aws_access_key_id: XXXXXXXXXXXXXX
  aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXXXX
  region: us-east-1
  from: satyam@polymath.network
  to: satyam@secureblocks.io
