language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
env:
  matrix:
  - SOLIDITY_COVERAGE=false
  global:
    secure: HHzid6sbf4Q/pJsvl1OJfhK9KE0BwqImyjv/cyqctXvhY+UZl7gGNL+YalPFzKrzP+7ws8JbUattUcacxRYHaErKauSAEheuFWM5TFSr4jTv3IwN8AGwxr3graKh0qQeNMoRzouhNCX2V757Te8TFGz69ghAV5SKHtCjMDCmhtImBFWKF1B9bc03uficA9kOdM9qZOq49vwOs8UQ8gCBqCd67559+ZeRAvn8BWHDx9+VLGGg+mWrWZpkPute0+802lsRLj4qFvGFdAVB/YcLCjQwo6QXTfR19E3o9+xTw4Shoq3yGjPMiu0SJmxDwYlvJRz3BPPksktY3/tyTCHlOz+TD+YhPmPdAjvSqeB2Nkooaw2KsG9tMjjf7XtfO1pv/B9MUobV0Dw1lIkJnek1OPHbjX5NpJjM25IxgVHi8f3a87dQc2XFEAbC+kkJ7or1Dgg2b1I5OEov7wi1A+nONZ2DgeTiGs4zotXTgqfXx661iJMxwn5FrmPWLwD7cT7voEfgKR6iVgANrgJqWu2RJyDkniET0yGdLaI1EdTeQkjHxD8UH4Aejt6GTxNDUnvcPYLfQyXKWKL/2LLKEc1yOriHJTBRi3AjzziG0ySOjrC4Atv/3apO+2ErqL2LmhV6rRTB09DTSPLfX6JFP8GYeSSaWWQ+C0xnLslsrZIkEvA=
matrix:
  fast_finish: true
  allow_failures:
  - env: SOLIDITY_COVERAGE=true
before_script:
- truffle version
script:
- npm run test
- npm run docs
notifications:
  slack:
    secure: W4FZSabLrzF74f317hutolEHnlq2GBlQxU6b85L5XymrjgLEhlgE16c5Qz7Emoyt6le6PXL+sfG2ujJc3XYys/6hppgrHSAasuJnKCdQNpmMZ9BNyMs6WGkmB3enIf3K/FLXb26AQdwpQdIXuOeJUTf879u+YoiZV0eZH8d3+fsIOyovq9N6X5pKOpDM9iT8gGB4t7fie7xf51s+iUaHxyO9G7jDginZ4rBXHcU7mxCub9z+Z1H8+kCTnPWaF+KKVEXx4Z0nI3+urboD7E4OIP02LwrThQls2CppA3X0EoesTcdvj/HLErY/JvsXIFiFEEHZzB1Wi+k2TiOeLcYwEuHIVij+HPxxlJNX/j8uy01Uk8s4rd+0EhvfdKHJqUKqxH4YN2npcKfHEss7bU3y7dUinXQfYShW5ZewHdvc7pnnxBTfhvmdi64HdNrXAPq+s1rhciH7MmnU+tsm4lhrpr+FBuHzUMA9fOCr7b0SQytZEgWpiUls88gdbh3yG8TjyZxmZJGx09cwEP0q7VoH0UwFh7mIu5XmYdd5tWUhavTiO7YV8cUPn7MvwMsTltB3YBpF/fB26L7ka8zBhCsjm9prW6SVYU/dyO3m91VeZtO/zJFHRDA6Q58JGVW2rgzO39z193qC1EGRXqTie96VwAAtNg8+hRb+bI/CWDVzSPc=
